placeholder for pr
microbiomedata/nmdc-schema pull request #1199
Opened 2023-10-18 18:45 UTC by turbomam

2023-10-18 19:57 UTC, turbomam commented
see 
- https://github.com/microbiomedata/nmdc-schema/pull/1201

2023-10-20 17:52 UTC, JamesTessmer commented
Added:
SubSamplingProcess class to [nmdc.yaml](https://github.com/microbiomedata/nmdc-schema/blob/1198-merge-subsampling-and-extraction-classes-with-data-that-illustrates-the-relationship-into-nmdc-schema/src/schema/nmdc.yaml)
Valid [data file](https://github.com/microbiomedata/nmdc-schema/blob/1198-merge-subsampling-and-extraction-classes-with-data-that-illustrates-the-relationship-into-nmdc-schema/src/data/valid/SubSamplingProcess-minimal.yaml)

Modified:
[sample_prep.yaml](https://github.com/microbiomedata/nmdc-schema/blob/1198-merge-subsampling-and-extraction-classes-with-data-that-illustrates-the-relationship-into-nmdc-schema/src/schema/sample_prep.yaml) due to slot definition conflicts, and previous discussion that we would redefine slots from sample_prep.

2023-10-20 21:46 UTC, cmungall commented on src/schema/nmdc.yaml
> +  volume:
give this a name that resolves ambiguity as to what volume is being referred to

2023-10-20 21:55 UTC, cmungall requested changes

2023-10-20 21:55 UTC, cmungall commented on src/schema/nmdc.yaml
> +    description: The volume of the solvent/solute being used, not the input.
Here we are defining a very general schema-wide slot `volume`; we can imagine this being used many places, e.g. volume of a container, of a piece of soil. But the description is very specific. Either do one of:

1. Make a more specific slot such as solvent_volume, and keep the definition
2. Keeping a generic volume, and amending this definition to be more generic, and putting the specific description on slot_usage in SubSamplingProcesss

2023-10-23 15:31 UTC, turbomam commented
Thanks James. Ina addition to @cmungall's request, could you please also add micro-crediting for yourself or others into the elements you want to merge (classes, slots, enumeration).

2023-10-23 19:43 UTC, JamesTessmer commented
Added the change to make volume more general, and add a more specific description in the slot usage. Also added credits for contributors.

2023-10-27 17:06 UTC, merged