Napa compliance
microbiomedata/nmdc-schema pull request #1246
Opened 2023-10-26 16:50 UTC by aclum

2023-10-26 16:53 UTC, aclum commented
linked issues https://github.com/microbiomedata/issues/issues/430 and [Re-ID NOM and Metabolomics OmicsProcessing, DataObjects, AnalysisActivies#524](https://github.com/microbiomedata/issues/issues/524)

2024-07-11 23:00 UTC, aclum commented
Closing since this merges to main-old, not main.

2024-07-15 20:36 UTC, eecavanna commented
I recommend moving these scripts into a subdirectory (e.g. `nmdc_schema/re_id_script`). I think that will distinguish them from general-purpose schema-related code. Note: Moving them might require updating some `import` statements.

2024-07-15 20:41 UTC, aclum commented
@turbomam  to suggest a different directory to put these scripts.

2024-07-15 21:04 UTC, aclum commented
Ideally it would be something more generic, I've had to make other ad hoc scripts  (ie https://github.com/microbiomedata/nmdc-schema/blob/main/nmdc_schema/identify_workflow_duplicates_emp500.py) for data clean up and I'd like this to be co-located.

2024-07-16 21:16 UTC, turbomam commented
@aclum I made a commit in this branch that moves the Python files and adds a few lines to the top of the README. If that's OK with you, then you can merge as far as I'm concerned.

2024-07-16 21:18 UTC, turbomam commented
Sorry, because I did a filesystem move and edited the README, no useful diff shows up 

here's what I added:

```
This code has been executed, the results were accepted, and it should not need to be run again. It is being included as
documentation. The Python files have been moved from `nmdc_schema/` to `nmdc_schema/completed_napa_compliance/` and they
shouldn't be expected to work from that location.

One shouldn't assume that the installation notes below are intended for any other nmdc-schema development.
```

2024-07-16 21:19 UTC, turbomam commented
oops, I missed your "more generic" comment too

2024-07-16 21:39 UTC, turbomam commented
@aclum @eecavanna I moved the scripts once again to `src/scripts/task_specific_code/` and added a little more to the README.md

Please let me know if this is acceptable to you

We can move [identify_workflow_duplicates_emp500.py](https://github.com/microbiomedata/nmdc-schema/blob/main/nmdc_schema/identify_workflow_duplicates_emp500.py) into `src/scripts/task_specific_code/` in a separate PR. That file isn't present in this branch.

2024-07-16 21:40 UTC, turbomam approved these changes

2024-07-16 21:49 UTC, eecavanna requested changes
I'm OK with the new folder name. I requested a change to some example commands, since they use the old folder name. 

Out sick this afternoon. Once the above is resolved, I'm OK with this being merged in without my involvement/review.

2024-07-16 21:49 UTC, eecavanna commented on src/scripts/task_specific_code/README.md
> +python -m black nmdc_schema/connect_napa_mongo.py
This still reflects the original path

2024-07-16 22:15 UTC, aclum commented
This is acceptable to me, I've addressed Eric's comments about the paths in the README.md file and have requested a re-review.

2024-07-16 22:20 UTC, eecavanna approved these changes

2024-07-16 22:23 UTC, merged