Initial  commit for branch, added filtration
microbiomedata/nmdc-schema pull request #1326
Opened 2023-11-09 21:46 UTC by JamesTessmer

PR to add filtration and phase separation classes and supporting slots.

2023-11-13 21:11 UTC, turbomam commented
Thanks for the new commit @JamesTessmer. Will you be updating the PR to address the error form the GH actions?

2023-11-13 22:17 UTC, JamesTessmer commented
> Thanks for the new commit @JamesTessmer. Will you be updating the PR to address the [error from the GH actions](https://github.com/microbiomedata/nmdc-schema/actions/runs/6855108387/job/18639473019?pr=1326#step:7:317)?

I am planning on fixing that later today, unfortunately i had some issues pop up today because of a power surge in our data center over the weekend so I won’t be able to touch this up until later today or early tomorrow.

2023-11-17 19:12 UTC, JamesTessmer commented
Build currently fails, but it should pass when main is merged in. Once any remaining build issues are addressed this should be ready for review.

2023-11-17 21:34 UTC, JamesTessmer commented
Merged main in, resolved all the conflicts. This should be ready for review.

2023-11-20 13:54 UTC, turbomam requested changes
Are any of the people contributing to this PR generating the documentation locally with `make testdoc`? That can be a really helpful for exploring the relationships between all of the terms added in a PR.

- What does it mean that a `FiltrationProcess` can have a `separation_method` relationship with a `ContainedInEnum`?
- What does it mean that a `FiltrationProcess` can have a `contained_in` relationship with a `ContainedInEnum`? I appreciate effort to use a verb-like slot name, but I really doubt you mean to say the `FiltrationProcess` is `contained_in` in something. Maybe something like `sends_output_into` would make more sense.
- Let's think about using the `ContainedInEnum` for other purposes. It really seems more like a ContainerCategoryEnum to me.
- What is a `MaterialContainer`? I may be the person who created that term, so I am willing to writ e description, but I will want your review. I think my intention here was to differentiate it from a data container, like the `Database` class.
- How can a `MaterialContainer` be `contained_in` in something? Maybe I have put too much pressure on you to be parsimonious with new slots. I think we need to say that
  - a `FiltrationProcess` `sends_output_into` some `ContainerCategoryEnum`
  - a `MaterialContainer` `container_category`  some `ContainerCategoryEnum`
- Are you sure we want to use strings (and not enumerations) for
  - `conditionings`
  - `filter_material`
  - `filtration_category`
- what can "either phase" in the `conditionings` slot `description` be? I assume solid, liquid or gas. Slot descriptions shouldn't require anyone to guess.
- we should add [list_elements_ordered](https://linkml.io/linkml-model/latest/docs/list_elements_ordered/)  to `conditionings`
- `instrument_used` needs a `description`. Do you want to do that or should I?
- `material` seems like an orphaned slot. Does anybody in metabolink remember what it was for?

2023-11-20 14:32 UTC, turbomam requested changes

2023-11-20 17:32 UTC, turbomam reviewed
I have updated the title of this PR so that it will be more informative in the auto-generated release notes.

2023-11-20 17:36 UTC, anastasiyaprymolenna commented on src/schema/nmdc.yaml
> +    permissible_values:
@mslarae13 Can you comment on how proportions should be indicated?

2023-11-20 17:47 UTC, anastasiyaprymolenna commented on src/schema/nmdc.yaml
> +  ConditioningSolventEnum:
This has been removed. It was missed when we removed the ConditioningValue class

2023-11-20 18:01 UTC, JamesTessmer commented on src/schema/basic_slots.yaml
> +      - annotate me!
Added "The device or tool that performed or aided in performing a process."

2023-11-20 18:03 UTC, JamesTessmer commented on src/schema/nmdc.yaml
> +  contained_in:
Updated the ContainedInEnum to be a ContainerCategory

2023-11-20 18:16 UTC, anastasiyaprymolenna commented
> Are any of the people contributing to this PR generating the documentation locally with `make testdoc`? That can be a really helpful for exploring the relationships between all of the terms added in a PR.
> 
> * What does it mean that a `FiltrationProcess` can have a `separation_method` relationship with a `ContainedInEnum`?
> * What does it mean that a `FiltrationProcess` can have a `contained_in` relationship with a `ContainedInEnum`? I appreciate the effort to use a verb-like slot name, but I really doubt you mean to say the `FiltrationProcess` is `contained_in` in something. Maybe something like `sends_output_into` would make more sense.

This stems from the fact that the way we have written the enum for Containers is very ambiguous so any slot that uses a container as it's range (meaning a process uses a container) it will have this relationship.

> * Let's think about using the `ContainedInEnum` for other future purposes. It really seems more like a ContainerCategoryEnum to me.

This has been updated accordingly.

> * What is a `MaterialContainer`? I may be the person who created that term, so I am willing to write a description, but I will want your review. I think my intention here was to differentiate it from a data container, like the `Database` class.
> * How can a `MaterialContainer` be `contained_in` in something? Maybe I have put too much pressure on you to be parsimonious with new slots. I think we need to say that
>   
>   * a `FiltrationProcess` `sends_output_into` some `ContainerCategoryEnum`
>   * a `MaterialContainer` `container_category`  some `ContainerCategoryEnum`


This comment relates to `sample_prep.yaml`. This file has existed since before MetaboLink started. We do not use anything here including `MaterialContainer`. We only comment out conflicts from here before a commit. We do not add to this file.

> * Are you sure we want to use strings (and not enumerations) for
>   
>   * `conditionings`
>   * `filter_material`
>   * `filtration_category`

These are not slots that inform any downstream processing, so its ok to not enforce Enums. It is more important to just note what was done in the details but not needed to filter down by a consistent value. Someone would want to be able to reference this info, but not query on it.

> * what can "either phase" in the `conditionings` slot `description` be? I assume solid, liquid or gas. Slot descriptions shouldn't require anyone to guess.

@mslarae13 this is a description we pulled from an ontology. I hesitate to change the language because it is specific to the reference (which we do not list in the description, but it is quoted)

> * we should add [list_elements_ordered](https://linkml.io/linkml-model/latest/docs/list_elements_ordered/)  to `conditionings`

Done

> * `instrument_used` needs a `description`. Do you want to do that or should I?

Done

> * `material` seems like an orphaned slot. Does anybody in metabolink remember what it was for?

Yes this is removed for this merge. It was prep for PhaseSeparation class.

2023-11-21 21:16 UTC, turbomam approved these changes
thanks everybody for the valuable discussions. I may raise some new issues about this, but I'm happy to merge this in now.

2023-11-21 21:16 UTC, merged