values in the `sample_link` slot may not always follow a formal syntax, like CURIe or GUID
microbiomedata/nmdc-schema pull request #1684
Opened 2024-01-18 21:54 UTC by bmeluch

From 
- https://github.com/microbiomedata/nmdc-schema/issues/1669

I updated the slot definition as described in the original issue, then updated the valid example files that already contained `sample_link` and created an invalid example file.

2024-01-22 15:35 UTC, turbomam reviewed
Thanks @bmeluch 

I expect that I can merge this in very soon, but I would like to touch base with you and any other stakeholders first.

Your examples illustrate three different kinds of relationships (as the prefix portion of the values), but is that an exhaustive list? Is there some documentation or code snippet that shows how the different kinds of relationships will be expressed in data? Where will we find the part of the sample linkage value that comes after the colon? Like, **which** slot of some other Biosample I guess?

2024-01-22 17:46 UTC, bmeluch commented
Hi @turbomam, 
Good question - I would have to double check with @mslarae13 about the complete list of relationships (before colon). I believe the part after the colon has to match `samp_name` (s) of the linked biosamples.

2024-01-30 23:53 UTC, mslarae13 requested changes

2024-01-30 23:53 UTC, mslarae13 commented on src/data/valid/Biosample-exhasutive.yaml
> +  - 'core: soil_core_O'
I would expect core to be source_mat_id. so i think this one should be removed. Maybe replace core with plant:

2024-01-30 23:53 UTC, mslarae13 commented on src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml
> +  - 'parent: example_samp_45'
parent is source_mat_id ... 1:1 parent to child. 
sample link is other sample types or horizontal relationships.. maybe make this one sibling:

2024-01-30 23:53 UTC, mslarae13 commented on src/schema/portal/sample_id.yaml
> +      - value: 'pooling: sample 1, sample 2, sample 3'
pooling is good!

2024-01-30 23:55 UTC, mslarae13 commented
@bmeluch ignore my comments until we chat. I need to review the NMDC schema and submission portal. source_mat_id needs some work. We can discuss this this week but I think we'll make a squad to do this.

2024-01-31 14:19 UTC, turbomam commented
> We can discuss this this week but I think we'll make a squad to do this.

Could I be part of this conversation?

2024-01-31 14:24 UTC, turbomam reviewed
I asked about the vocabulary of relationship types before, but now I think we need to discuss the overall grammar, and what agent (person or software) is responsible for interpreting it.

It wouldn't be too hard to do that with structured objects in the nmdc-schema, but it  will be harder in the flattened submission-schema. Are you planning on allowing different relationships to be semi-colon delimited in the DH cells? Will there be any entry-time validation?

2024-01-31 14:24 UTC, turbomam commented on src/data/invalid/Biosample-invalid-linkage.yaml
> +sample_link:
is this a list of three free stating strings and an integer?

2024-01-31 14:34 UTC, turbomam commented
We defined `sample_link` in `src/schema/portal/sample_id.yaml`, so we can do whatever we want with it, right? Let's start making a distinction between a more structured modeling in nmdc-schema and move this flattened approach to the submission-schema, where it will be totally relevant and appropriate.

2024-05-22 20:54 UTC, bmeluch commented
This is now way out of date, and we need more discussion on `sample_link` - closing this but will leave the issue open and start a new PR when the discussion comes back around.

2024-05-22 20:54 UTC, closed without merging