Project id patterns
microbiomedata/nmdc-schema pull request #1994
Opened 2024-05-22 16:20 UTC by turbomam

2024-05-22 16:46 UTC, turbomam commented
There are still many appearances of 'xx' or 'generic:' in the valid examples data, especially for `has_raw_value` and `has_output`

2024-05-22 19:02 UTC, turbomam commented
@aclum 

with the addition of the mentioning slot pattern constraints, `nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml` doesn't really accept mentioned legacy ids anymore.  That's really apparent in `local/mongo_as_nmdc_database_validation.log` generated by `make-rdf`

2024-05-22 20:09 UTC, turbomam commented
`nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml` is tolerant of legacy `id`s in any position now

2024-05-30 18:38 UTC, aclum commented on src/data/valid/Database-extraction_set-exhaustive.yaml
>        - generic:xxx
If we've done things correctly generic:xxx should not be valid for has_output for this class. It should only allow an instance of Class ProcessedSample.

2024-05-30 18:45 UTC, aclum commented on src/data/valid/Database-extraction_set-minimal.yaml
>        - generic:yyy
Same comments as on src/data/valid/Database-extraction_set-exhaustive.yaml, this example data will need to be updated once the range of has_output is fixed.

2024-05-30 18:47 UTC, aclum commented on src/data/valid/Database-library-prep-exhausive.yaml
>        - generic:xxx
Same comments here Class LIbraryConstruction, class range for slot_has output needs to be updated to [ProcessedSample](https://microbiomedata.github.io/berkeley-schema-fy24/ProcessedSample/) and example data needs to be updated.

2024-05-30 18:50 UTC, aclum commented on src/data/valid/Database-metagenome-assembly.yaml
> +    #    was_informed_by: nmdc:act-11-547rwq94.1 # should this allow an omics processing as the informer? what about act? that's abstract isn't it?
They way this slot is being used in practice is to tie WorkflowExecutionActivity subclass instances to OmicsProcessing & this is what the data portal uses The instances themselves are linked by has_input and has_output. We shouldn't make any further changes to this now b/c WorkflowChain in Berkeley schema addresses this.

2024-05-30 18:52 UTC, aclum commented on src/data/valid/Database-nucleic-extraction.yaml
>      has_output:
Same as PlannedProcess subclasses, range for has_output needs to be updated to PlannedProcess and example data needs to be updated.

2024-05-30 18:53 UTC, aclum commented on src/data/valid/Database-pooling_set-exhaustive.yaml
>        - generic:xxx
Pooling has_output range needs to be updated to ProcessedSample and example data updated.

2024-05-30 18:55 UTC, aclum commented on src/data/valid/Extraction-proteomics.yaml
>    - "nmdc:ome-39"
Same comment here, this has_output value should not be valid under any circumstances b/c there is no blade and will become invalid once you update the range of has_output to PlannedProcess.

2024-05-30 18:57 UTC, aclum commented on src/data/valid/Pooling-exhaustive.yaml
>    - generic:xxx
Will need to fix this example data.

2024-05-30 18:59 UTC, aclum commented on src/schema/nmdc.yaml
> +          syntax: "{id_nmdc_prefix}:(bsm|procsm)-{id_shoulder}-{id_blade}"
Missing closing $

2024-05-30 19:02 UTC, aclum commented on src/data/valid/DataObject-exhaustive.yaml
> +was_generated_by: "nmdc:act-99-123456.1"
Update to WorkflowExecutionActivity subclass instance. Activity is abstract so won't mint an identifier.

2024-05-30 19:03 UTC, aclum commented on src/schema/nmdc.yaml
> +          syntax: "{id_nmdc_prefix}:(act|wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc|wf|omprc)-{id_shoulder}-{id_blade}{id_version}$"
remove act, Activity is an abstract class now so won't mint IDs.

2024-05-30 19:06 UTC, aclum commented on src/schema/prov.yaml
> +          #          syntax: "{id_nmdc_prefix}:(act|wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc|wf)-{id_shoulder}-{id_blade}{id_version}$"
remove 'act', Activity is abstract now.

2024-05-30 19:10 UTC, aclum requested changes
We need to tighten the constraints on the range for has_output on PlannedProcess subclasses to ProcessedSample and remove references to Activity as an identifier b/c that is abstract now. See individual comments for details.

2024-05-31 18:08 UTC, turbomam commented on src/data/valid/Extraction-metabolomics.yaml
>    - "nmdc:ome-8"
isn't 'abcdef' the blade? 'nmdc' is the prefix, 'procsm' is the typecode, '99' is the minting authority, and  'abcdef' is the blade, right?

2024-05-31 23:20 UTC, merged

2024-06-03 17:51 UTC, aclum commented on src/schema/nmdc.yaml
> +          syntax: "{id_nmdc_prefix}:(wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc|wf|omprc)-{id_shoulder}-{id_blade}{id_version}$"
'wf' should be removed, WorkflowExeuctionActivity is abstract. id_version should be allowed on workflow activity subclasses but not OmicsProcessing records so I think this should be re-written like this
syntax: "{id_nmdc_prefix}:(wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc)-{id_shoulder}-{id_blade}{id_version}$ | {id_nmdc_prefix}:omprc-{id_shoulder}-{id_blade}$"

2024-06-03 17:56 UTC, aclum commented on src/schema/prov.yaml
> +    structured_pattern:
Same comments as on slot was_generated_by on Class DataObject. 'wf' should be removed, WorkflowExeuctionActivity is abstract. id_version should be allowed on workflow activity subclasses but not OmicsProcessing records so I think this should be re-written like this
syntax: "{id_nmdc_prefix}:(wfmag|wfmb|wfmgan|wfmgas|wfmsa|wfmp|wfmt|wfmtan|wfmtas|wfnom|wfrbt|wfrqc)-{id_shoulder}-{id_blade}{id_version}$ | {id_nmdc_prefix}:omprc-{id_shoulder}-{id_blade}$"
Can we just define this globally on the slot and then remove the local definition on Class DataObject?