1000 model rna library preparation
microbiomedata/nmdc-schema pull request #2113
Opened 2024-07-09 19:07 UTC by aclum

This PR is to model how to capture RNA-seq library preparation information which is needed input for the expression step of the Metatranscriptome analysis workflow.

2024-07-15 18:23 UTC, turbomam commented
Thanks @aclum! I prefer the explicitness and atomicity of the `is_stranded` and `stranded_orientation` style. That option only adds one slot beyond the other option, right?

2024-07-15 22:10 UTC, eecavanna requested changes
> Changes are additive, no migrators needed.

I agree. This schema change adds a non-required slot named `is_stranded` to an existing class, adds a non-required slot named `stranded_orientation` (whose range is an enum) to that same class, and defines that enum. None of that has the potential to make currently-valid data become invalid, which is what I consider to be the condition for whether a migrator is necessary or not.

I'm requesting a couple changes related to the spelling of "orientation". I don't have any other concerns about these changes.

2024-07-15 22:10 UTC, eecavanna commented on src/schema/nmdc.yaml
> +  StrandedOrentationEnum:
I think there is a typo in the name of this enum:

```suggestion
  StrandedOrientationEnum:
```

2024-07-15 22:10 UTC, eecavanna commented on src/schema/nmdc.yaml
> +    range: StrandedOrentationEnum
I think there is a typo in the name of the enum:

```suggestion
    range: StrandedOrientationEnum
```

2024-07-15 23:58 UTC, eecavanna approved these changes
All of my concerns have been resolved. I'm comfortable with this being merged in.

2024-07-16 16:05 UTC, aclum commented
Discussed at the workflows meeting and there were no concerns.

2024-07-16 16:18 UTC, turbomam commented on src/schema/nmdc.yaml
> +      antisense orientation:
actually, could we please add descriptions to these permissible values?

2024-07-16 20:09 UTC, turbomam approved these changes
nice

2024-07-16 20:15 UTC, merged