updates to MagsAnalysis slots
microbiomedata/nmdc-schema pull request #2225
Opened 2024-10-18 00:46 UTC by aclum

Add descriptions and mappings, add enum for bin quality range.

# PR Information

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation
- [x] Schema change: Structure and content
  - created, updated, or deleted a `class`, `slot`, or `enum`
  - changed whether a `slot` is `multivalued`
  - changed the way a `slot` is assigned to a `class`
  - changed the `permissible_values` of an `enum`
  - _etc._
- [ ] Schema change: Cleanup and preparation
  - updated the description of a `class`, `slot`, or `enum`
  - updated the `mappings` of a `class`, `slot`, or `enum` to an ontology
  - added an `enum` for _future_ use (it is not in the `range` of any `slot`)
  - _etc._
     
## Description

> _PRs should be [small and concise](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs)._
>
> Aim to create small, focused pull requests that fulfill a single purpose. Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and provide a clearer history of changes.

- Replace this text with a description of what this PR branch contains. Please keep in mind that all reviewers will be reading this description. Example: "In this branch, I..."

## Related Issues

> All PRs should relate to or fix an issue(s). Please identify the issue(s) below.

- Related Issue(s): #
- Fixes: #2160 

## Did you add/update any tests?

- [ ] Yes
- [ ] No _(Add a justification below)_
- [ ] I need help with writing tests

## Could this schema change make it so any valid data becomes invalid?

> This is a question about what the schema allows. It is not a question about what happens to exists in the NMDC database right now.
> 
> Example: If, in this PR branch, you renamed a `slot` from `foo` to `foo_bar`, the answer to this question would be "yes," **even if** nothing in the NMDC database _currently_ uses the `foo` `slot`.
>
> More examples: `slot` or `class` name changes, changes to a `slot`'s `multivalued` state, changes to a `slot`'s `range` (e.g. string to integer), changes to `slot` assignments to `class`es, changes to an `enum`'s `permissible_values`

- [ ] Yes _(A migrator is required)_
- [ ] No
- [ ] I need help determining this

## If you answered "Yes", does this PR branch include that migrator?

- [ ] Yes
- [ ] No, this PR is incomplete and I need help writing the migrator

## Does this PR have any downstream implications?

> Examples: any change here that requires a change to workflows, workflow automation, the Mongo-to-Postgres ingest process, Jupyter notebooks, the Runtime, etc.

- [ ] Yes _(Explain below)_
- [x] No

2024-10-18 00:47 UTC, aclum commented
@turbomam can you point me to an for setting a range to only positive integers?

2024-10-21 17:37 UTC, turbomam commented on src/schema/core.yaml
> -    todos:
thanks ofr taking this initiative

2024-10-21 17:39 UTC, turbomam requested changes

2024-10-21 17:39 UTC, turbomam commented on src/schema/core.yaml
> +    comments: https://doi.org/10.1093/bioinformatics/btz848
`comments`  is `multivalued`, so it takes a list of values. `see_also` is a better choice for capturing a URL, and it is also `multivalued`. So for `gtdbtk_domain` I recommend

```yaml
gtdbtk_domain:
    description: Taxonomic domain assigned by GTDB-Tk.
    comments: https://doi.org/10.1093/bioinformatics/btz848
    range: string
    exact_mappings:
      - NCBITaxon:superkingdom
```

2024-10-21 18:45 UTC, turbomam approved these changes

2024-10-28 17:20 UTC, merged