Modify range of identifiers fields to be uriorcurie
microbiomedata/nmdc-schema pull request #861
Opened 2023-04-12 06:45 UTC by sujaypatil96

Fixes #821

2023-04-12 12:48 UTC, turbomam commented
Thank you. Can you please also add a an invalid example data file that is very obvious about the fact that id prefixes are missing? One of the id values could be 'unprefixed', and the file could have a name like src/data/invalid/Biosample-unprefixed-id.yaml

2023-04-12 12:59 UTC, turbomam requested changes

2023-04-12 12:59 UTC, turbomam commented on src/data/valid/Biosample-exhasutive.yaml
> +  - prefix:any string 1
Let's use a prefix that's defined in the schema. I think there are some cases in which using an undefined prefix causes problems. Maybe converting data to RDF TTL?

2023-04-18 20:56 UTC, turbomam requested changes

2023-04-18 20:56 UTC, turbomam commented on src/data/invalid/Biosample-invalid_identifiers.yaml
Thanks for the invalid file. I just can't tell what the invalid parts are. Can you please base your examples on the minimal example, and only introduce one invalid property per file? That obviously may require a large number of invalid files, with more indicative names.

2023-05-15 17:37 UTC, sujaypatil96 commented
Question to self: `alternative_identifiers` has a number of child slots like `gold_identifiers`, `imgnify_identifiers`, etc. If `required: true` and `multivalued: true` are being applied to `alternative_identifiers` already, then ideally the children should inherit those properties as well. Make sure that this is the case and remove redundant explicit assertions of those properties in the children slots.

2023-06-08 03:02 UTC, turbomam commented
@sujaypatil96 I have added consistent range, pattern and multivalued properties to the `external identifier` type and the `external_database_identifiers` parent slot in src/schema/external_identifiers.yaml as part of https://github.com/microbiomedata/nmdc-schema/pull/964. 

I believe we can close this PR and any related issue.

```yaml
types:

  external identifier:
    typeof: uriorcurie
    description: >-
      A CURIE representing an external identifier
    see_also:
      - https://microbiomedata.github.io/nmdc-schema/identifiers.html
    pattern: '^[a-zA-Z_][a-zA-Z0-9_]*:[a-zA-Z_][a-zA-Z0-9_]*$'

slots:

  external_database_identifiers:
    abstract: true
    description: Link to corresponding identifier in external database
    is_a: alternative_identifiers
    multivalued: true
    pattern: '^[a-zA-Z_][a-zA-Z0-9_]*:[a-zA-Z_][a-zA-Z0-9_]*$'
    range: external identifier
    comments:
      - The value of this field is always a registered CURIE
    notes:
      - "had tried ranges of external identifier and string"
    close_mappings:
      - skos:closeMatch
```

2023-10-24 20:46 UTC, turbomam commented
@sujaypatil96 do you want to leave this PR and it's corresponding branch open?

2023-10-27 16:52 UTC, sujaypatil96 commented
We should be good to close this PR @turbomam. The fix that you have in #964 took care of all the external identifiers slots that I was trying to update individually. Your modeling fix that updated the range of `external_database_identifiers` to `external identifier` is a more elegant one 💯

2023-10-27 16:52 UTC, closed without merging